version: '3.9'

services:
  arango:
    image: arangodb:3.12.0.2
    container_name: arango
    ports: 
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=admin123
    volumes:
      - arangodb:/var/lib/arangodb3
    networks:
      - backend
     
volumes:
  arangodb:
    
networks:
  backend: